#+STARTUP: indent

* SQL group-concat
** [[http://stackoverflow.com/questions/2560946/postgresql-group-concat-equivalent][Postgresql GROUP_CONCAT equivalent?]]

* 알고리즘 (Java로 구현)
** quicksort
** mergesort
** heap
** bubble sort

* 인생 - 왜 편하게만 살려고 할까? 왜 돈만 많이 벌려 할까?

* 거짓 일정

* 소설, 만화, 소프트웨어 개발
소설의 경우 여러 작가가 한 작품을 쓰는 경우가 거의 없다.

만화의 경우는 스튜디오에서 여러 명이 한 작품을 작업하는 경우가 있다. 아마 전체 줄거리라 스토리 전개는 한 명이 담당하고 나머지는 그에 맞게 그림을 그리는 작업을 할 것이다.
만약 팀원 중 한 명이 등장인물의 성격이 마음에 들지 않는다고 해서 중간에 자신의 입맛에 맞게 성격을 바꾼다고 하면 스토리 전개가 엉망이 될 것이다.

만화에서 실제 작업 분담을 어떻게 하는지? 어떻게 알 수 있을까?

프로그램은 단순한 코드 집합이 아니라 사고 체계의 집합이라 할 수 있다. 문제 영역을 분석하고 이해하기 위한 사고 체계의 집합. 문제를 나누는 방법, 추상화하는 방법은 팀 내 합의에 의해 이루어져야 한다. 새로 추가된 팀원이 문제를 나누고 추상화하는 방법이 마음에 들지 않는다 하여 자신의 입맛대로 고친다면... 재앙이 발생할 것이다.

* 회사 일이 재미있으려면
  1) 중요 사항에 대한 결정 권한이 있어야 한다. 다른 사람이 시키는 대로만 하면서 재미있기는 어렵다. 자신의 아이디어를 넣을 수 있어야 한다.
  2) 의미있는 일을 해야 한다. 한 일이 아무런 의미도 없는 일이라면 재미있을 수가 없다.

* 퇴근 후 업무
** [[http://media.daum.net/society/others/newsview?newsid%3D20150930031549456][퇴근 후에도 업무 메신저 폭주.. "연락 안받을 권리 없나요"]]

* Emacs를 REST 클라이언트로 사용하기
** [[http://emacsrocks.com/e15.html][Emacs Rocks! Episode 15: restclient-mode]]
** [[https://github.com/pashky/restclient.el][pashky/restclient.el]]

* 쿠팡
** 평가
*** 직원 동기부여 보다는 평가만 중요시하는 CTO
** 커뮤니케이션
*** 비공식적 커뮤니케이션이 많아 일이 어떻게 진행되는지 파악하기 어렵다.
*** API 같은게 바뀌어도 릴리즈 노트 비스무리 한 것도 없음. 그냥 메일로 뚝.
*** ..
* 아마존
** 시작
*** 아마존 리쿠르터에게서 연락 옴.
*** 내 이력이 흥미롭다며 한국에서 채용 이벤트를 할 계획인데 관심 있냐? 아마존에서 내 이력의 어떤 부분에 흥미를 느꼈는지 모르겠지만 관심 있다고 대답.
** 전화통화
*** 지난 번 블리저드 지원했을 때 전화 인터뷰를 해봤기 때문에 대충 알아들을 수 있을거라 기대.
*** 인터뷰인줄 알고 긴장했으나 간단한 인적 사항 (학위, 프로그래머 맞는지 등) 확인. 채용 이벤트에 대한 설명.
*** 리쿠르터 영어 알아듣기 힘들었음. 과연 내가 합격할 수 있을까 의문.
** 과제
*** 간단한 프로그래밍 퀴즈 문제. 긴장하고 풀었음. 대략 4시간 안에 풀 수 있으며 잘 하는 사람은 1시간 반 정도에 풀었다고 함.
*** 코드 작성 뿐 아니라 주석 작성, 복잡도 분석, 테스트도 필요.
*** 코드는 금방 작성했으나 주석, 복잡도 분석, 테스트 작성에 시간 많이 걸림.
** 인터뷰 안내 전화
*** 기술 인터뷰니 복장 편하게 입고 오라고. "네 프로그래밍 실력을 보려는 것이지 복장을 보려는 게 아니다."
*** 인성 면접 아니라고 강조.
*** 인터뷰 가이드라고 파일을 보내줬는데, 내용이 "자료구조, 알고리즘, 데이터베이스, 네트워크, 분산시스템, 등등..." 다 보려면 몇 년은 걸리겠다!
*** 알고리즘 퀴즈 풀기로 준비. 퀵소트, 머지소트 등 자바로 작성 연습...
*** 목표: 망신만 당하지 말자...
** 인터뷰
*** 그랜드 하야트 호텔. 그렇게 긴장하기는 처음.
*** 물병도 주고 기다리는 동안 보라고 킨들 파이어 주고 감. 네트워크 안 되니 할 수 있는게 없음. 왜 준거야?
*** 면접1
**** 나이가 지긋해 보이는 분
**** 책도 썼냐며 좋아함
**** 영어 실력을 평가하려는게 아니니 혹시 알아듣지 못했으면 부담갖지 말고 물어보라고 함.
**** 자료구조, 각 자료구조 복잡도 질문
**** 트리 순회 코드 작성. 재귀를 사용해 간단하게 풀었더니 재귀를 사용하지 말고 풀어보라고... 스택을 써서 풀어보려다가 실패. 젠장!!!
**** 문제가 점점 어려워짐
**** 결국 버벅... 제대로 답한건가?
*** 면접2
**** 여자 면잡관
**** 간단한 코딩 퀴즈. 예전에 봤던 문제. 면접관에게 예전에 봤던 문제라고 말했더니 "그럼 다른 문제로 바꿔줄까?" 하길래 "그냥 풀어볼께요." 했음
**** 면접관에게 이러이러하게 풀겠다 이야기했음. 사실 clojure로 풀었으면 말한대로 풀기가 쉬웠겠지만 java로는 그게 그렇게 단순할지 의문... 면접관이 그러지 말고 그냥 for 루프 써서 풀어보라고...
**** 어렵지 않게 풀었는데... 면접관이 코드 실행 결과를 화이트보드에 적어보라고... 적다보니 버그 발견! 잽싸게 코드 수정... 면접관이 잘 했다고 함.
**** 두 번째 문제도... 예전에 봤던 문제. 물론 이것도 풀어보지는 않았던... 시간이 충분하지 않으므로 코드를 적는 대신 어떻게 풀지 알고리즘으로 설명하겠다고 하고 주저리 주저리 설명... 면접관이 내 알고리즘으로 처리 안 되는 문제 지적... 보완해서 다시 설명... 면접관이 잘 했다고 함.
*** 면접3
**** 객체지향 면접
**** 젋어보이는 남자 면접관이었는데 말을 알아듣기가 매우 힘들었음. 어쩔 수 없이 계속 다시 설명해달라고...ㅠㅠ
**** 문제를 이해한 다음 클래스 다이어그램을 그려가며 논의
**** 요구사항이 추가되고 리팩터링 하면서 클래스 다이어그램을 수정해감
**** 면접관이 잘 했다고 함.
*** 면접4
**** 매우 어려워 보이는 남자 면접관
**** 뜬금없이 OO 시스템을 설계해보라고 함. 매우 난감...
**** 그냥 화이트보드에 그림 그리면서 설명하기 시작...
**** 요구사항을 계속 추가...
**** 면접관이 아주 잘 했다고 함.
*** 면접이 모두 끝나고 나오면서 "정말 좋은 경험을 했다. 꼭 붙고 싶다." 생각. 안내하는 분에게 "당신을 다시 보고 싶다."고 말하면서 나옴.
** 합격
*** 기다리는 동안 매우 초조... 면접 당시에는 그럭저럭 잘 했다고 생각했는데, 결과를 기다리면서 면접 때 잘못 대답한 것이 계속 생각남.
*** 미국에서 합격 메일...
*** Offer 옴. 리쿠르터가 어느 정도 연봉을 받고 싶냐고 하길래 OO 정도는 됐으면 좋겠다 했더니 비웃는 느낌... 결국 내가 부른 것보다 조금 더 줌. 더 높게 부를껄 그랬나?
*** 리쿠르터가 "내년 10월부터 일 할 수 있다"고 말함. 헉! 그럼 거의 1년을 기다려야 한다고??? 알고보니 비자 때문에 어쩔 수 없음.
** 계약 및 이후 진행
*** 계약, 세금, 이사, 비자, 주거 관련해 여러 담당자에게 계속 메일이 오고 전화 통화...
*** 기술 이외의 부분에 대해 영어로 대화할 때 머리 깨지는 줄 알았음.
** 비자
*** 미국 취업 비자 신청시 석사가 유리하다고 함. 그래서 석사인지 확인했구나.
*** 그런데 석사라 해도 된다는 보장은 없음. 알아보니 2014년에 60% 정도... 그럼 안 될 확률이 40%란 말이야??? 2015년은 더 빡셀 것으로 예상ㅠㅠ
*** 리쿠르터에게 메일 옴. 비자 지원자가 너무 많아 비자를 받는다는 보장이 없음. 비자 안 나오면 다른 나라에 있는 아마존에 지원할 수 있게 Ireland, Germany, Netherlands, Spain, Canada, UK, France, Romania, South Africa, India, China, Japan 중 세 나라 선택하라고. 아는 외국어라곤 딸랑 영어 하나이므로 영어 사용 국가인 Canada, UK, Ireland 선택해 답장.
*** 그래도 되겠지... 기대...
*** 그 와중에 Amazon Prime 팀(캐나나)에서 서울에 온다고 지원할 생각 없냐고 링크드인을 통해 메일 옴. 혹시 내가 캐나다를 선택한 것과 관련 있는지 내 리쿠르터에게 물어봤더니 잘못 보낸 거라고...
*** 결과가 나올때가 됐지만 연락 없음. 리쿠르터에게 기다리라고 메일 옴. 초초하게 계속 기다림.
*** 비자 에이전트에서 연락 옴. 비자를 받은 사람들에게는 연락이 다 갔다, 비자 로터리에서 당첨되지는 않았지만 혹시 빈 자리가 생길 수도 있으니 희망을 잃지 마라는 취지의 메일 옴. 안 되나....
*** 비자 로터리에서 당첨되지 않았음을 확인하는 메일 옴. 좌절...
** 다시 온 기회
*** 쿠팡은 너무 지겨워 다른 회사를 알아보기 시작. 한 회사에 면접 보고 가기로 결정하기 직전 다시 아마존에서 연락 옴.
*** 미국 비자가 안 나온게 최종 확인되어 아마존UK에 소개해 주겠다고.
*** 반신반의 했지만 일단 진행해보기로. 면접 본 회사에는 못 가게 되었다고 연락함.
*** 아마존UK 리쿠르터와 메일...
*** 미국 비자 안 나와서 좌절했는데 영국도 그런거 아니냐 물었더니 영국은 비자 심사가 훨씬 투명하며 기간도 빠르다고 함.
*** 리쿠르터가 내 경력과 맞을 것 같은 팀을 간단히 소개하며 관심가는 팀을 선택해 알려달라고 함. 리쿠르터가 말한 팀 중 하드웨어 관련 팀을 제외한 네 팀을 선택
*** 리쿠르터가 각 팀 매니저와 일정을 조율해 내게 팀 소개할 시간을 알려줌.
** 팀 소개: 각 팀마다 대략 1시간 정도의 소개를 받음.
*** Purchasing TVOD
*** Website
**** 처음에는 제일 관심이 가는 팀
**** 매니저도 매우 친절하게 설명
**** 매니저에게 미안했지만 Mason이란 처음 듣는 프레임워크를 사용한다는 말에 안 가기로...
*** Client Service
**** 하는 일이 가장 마음에 들었음
*** Finance Systems
**** Client Service로 마음을 굳힌 상태에서 면담,
**** 여러 가지 신기술을 사용하는 것 같으나, 내부 시스템을 개발하는 팀인듯 하고 Ruby on Rails를 사용한다는 말을 듣고 접음.
** 연봉 협상
*** 리쿠르터가 대략적 시세를 조사해보라고 했으나 아무리 찾아도 도움되는 자료를 찾지 못함. 영국이 미국보다 급여 수준이 낮다는 것만 확인
*** 실제로 많이 줄어들었음. 그리고 RSU도 많이 줄어듬. 작년 말 오퍼를 받았을 때보다 아마존 주가가 크게 올랐기 때문인 것으로 추정. 금액으로 따지면 대략 비슷.
*** 선택의 여지가 없어 수용함.
** TB 테스트
*** 신촌 세브란스에서 TB 테스트
*** 어른 8만원, 어린이 5만원... 테스트 비용만 26만원...
** 영어시험: IELTS
*** 헉! 영어 시험을 봐야 한다고? 영어 공부 끊은지가 언젠데...ㅠㅠ
*** 그 와중에 이사, 세금, 지역 컨설턴트가 연락옴 => 모든 논의를 영어 시험 이후로 미룸
*** UKVI 테스트 비용 36만원...
*** UKVI 가능한 가장 빠른 날 (9/12)로 선택. 공부할 시간이 없다...
*** 밤, 주말에 공부... 일단 IELTS가 어떤 시험인지 파악...
*** 듣기와 읽기는 대략 하겠는데... 쓰기와 말하기가 문제... 내가 잘 모르는 주제에 대해서는 한국어로도 할 말이 없는데 이걸 영어로 어떻게...
*** 듣기, 읽기는 무사히 넘김. 쓰기도 할 말이 있는 주제로 나와서 다행... 말하기는 5시20분... 그동안 뭐하지...
*** 말하기... 인사하고... 사진에 대해서 물어보네... 별로 할 말이 없는데... 헉 카드에 수공예에 대해서... 이건 정말 할 말이 없네ㅠㅠ 어떻게 버벅버벅...
*** 성적: overall 6 나옴. 처음 목표가 6이었으므로 3주 벼락, 그것도 아주 열심히 한 것은 아니니 만족할만한 결과지만, 조금 더 잘봤으면 6.5 나올 수 있었는데 하는 아쉬움... 사람 마음 참 간사하다.
** 비자 신청
*** 영어 점수 확보로 비자 신청
*** 비자 에이전트가 80페이지 분량의 신청서를 보내줌... 내용 다 확인하고... 복사하라고...
*** VAC에 접수
**** 복사본은 돌려받을 서류에 대해서만 제출하면 됨
**** 사진 따로 낼 필요 없음 (신청서에 붙어있는 걸로 충분)
**** 중간 뭉텅이 서류는 온라인 신청으로 바뀐 이후부터 불필요
*** 결과
**** 10/08 접수
**** 10/12 "A decision has be made..." 메일. 젠장 무슨 결정?
**** 10/13 여권 찾아가라는 메일... 비자 나온거야, 안 나온 거야? 초조...
**** 10/14 VAC 방문 여권 찾음. 비자 나옴...ㅠㅠ
** 이주 준비
*** 사전 조사
**** 살인적인 물가
***** 월세 한 달에 180만원...
***** 교통비 한 달에 50만원...
***** 아이 도우미... 매우 비쌈... 아내에게 미안...
***** 과연 좋은 걸까? 삶의 질이 너 나빠지는 것 아닐까?
***** 미국보다 급여는 줄었는데 물가는 더 높다.
*** 세금
**** 세금 관련 문제는 국어로 읽어도 복잡하고 이해하기 어렵운데 이걸 영어로 읽으려니... 돌아버리겠다.
*** 이사
**** 이사 컨설턴드와 전화 통화
**** 문서 잔득 보내줌. 모두 영어ㅠㅠ. 언제 다 읽어? 게다가 사인해서 스캔해 보내란다.
* 글쓰기
예나 지금이나 글을 쓰는 것은 쉬운 일이 아니다. 초등학교때 방학 숙제 중 제일 싫은 게 글짓기 숙제였다. 항상 개학 직전까지 안 하고 버티다가 막판에 어거지로 하곤 했다. 초중고 글짓기 숙제든 대학교 보고서든 가장 어려운 것은 시작이었다. 어떻게든 쓰기 시작 하면 그럭저럭 써 나갈 수 있었다.

지금은 그때처럼 억지로 글을 쓰지 않는다. 오히려 자발적으로 글을 쓰고 있다. 그러나 글을 쓰는 데는 여전히 많은 시간이 든다. 간단한 아이디어만 끄적거리다 마무리하지 못하는 경우도 많다.

가장 큰 문제는 주의력 분산에 따른 집중력 저하다.

이제는 예전처럼 종이에 글 쓰는 일이 많지 않다. 간단한 메모 정도만 종이에 끄적거릴뿐 글은 대부분 컴퓨터를 이용해 쓴다. 종이에 글씨를 쓰는 것보다 자판을 두드리는게 훨씬 빠르다. 다만 컴퓨터로 글을 쓸 때는 글쓰기에만 온전히 집중하지 못하고 주의력이 분산된다. 뭘 쓸까 생각하다 진도가 안 나가면 트위터나 스택오버플로우에 새로운 게 올라왔나 확인한다. 그렇게 시간을 보내다 다시 글쓰기로 돌아온다. 잠시 몇 글자 끄적이다 이내 인터넷 뉴스를 본다. 이런 식이다 보니 글쓰기가 잘 될 턱이 없다. 뭔가 써야지 하고 한 시간을 책상에 앉아 있어도 단 한 글자도 못쓸 때가 많다.

글쓰기에 컴퓨터를 사용하는 것은 컴퓨터에서 작업하는 편이 최종 출판 매체에 접근하기가 쉽기 때문이다. 종이에 적었다면 어차피 그걸 다시 컴퓨터로 옮겨야 할 것이다. 생각해보니 세상이 많이 달라졌다. 예전에는 컴퓨터로 문서를 작성했더라도 종이로 출력해 제출해야 했는데, 요즘은 공식적인 서류 제출할 때 말고는 프린터를 사용하는 일도 없는 것 같다.

한동안 내가 글을 쓰지 못하는 것은 시간이 충분하지 않기 때문이라 생각했다. 곰곰이 생각해보니 꼭 시간 때문은 아닌 것 같다. 그건 손쉬운 핑계거리였을 뿐이다. 글을 쓰겠다 해놓고 실제로는 트위터나 인터넷 뉴스를 보며 시간을 보낸 것이다. 제일 큰 문제는 집중하지 못한 것이었다.
